default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  # host: localhost
  socket: /run/mysqld/mysqld.sock

development:
  <<: *default
  database: rails_example_development

test:
  <<: *default
  database: rails_example_test

production:
  <<: *default
  database: rails_example_production
  username: rails_example
  password: <%= ENV["RAILS_EXAMPLE_DATABASE_PASSWORD"] %>
  # host: localhost
